#  Name of workflow
name: Production workflow

# When workflow is triggered
on:
  push:
    tags:
      - "v*"

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v1
      # Install NodeJS
      - name: Use Node.js 16.13.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.x
      # Run npm install and build on our code
      - run: npm install
      - run: npm run build --if-present
      # Deploy to Netlify using our production secrets
      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.DEV_NETLIFY_SITE_ID }}
          SHOPIFY_DOMAIN: uoonastore.myshopify.com
          SHOPIFY_STOREFRONT_TOKEN: 6f72a1d2317a72216d8718e937f03f8d
          SITE_KEY: 6LdyOQklAAAAAMwCqEqpmgSzd4YKPA2LCqgpSE3Z
          SECRET_KEY: 6LdyOQklAAAAAPio6Su6Rj80CH8nLDNU4qh_QGCu
        with:
          args: deploy --dir=build --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'